In [9]:
import duckdb
import pandas as pd

In [18]:
sql_query = '''
SELECT schema_name
FROM information_schema.schemata
ORDER BY schema_name;
'''

with duckdb.connect('../posts_data.duckdb') as con:
    display(con.sql(sql_query).df())

               schema_name
0       information_schema
1          ingest_api_data
2  ingest_api_data_staging
3                     main
4                     main
5                     main
6               pg_catalog

In [26]:
sql_query = '''
use ingest_api_data;
show tables;
desc posts;
select user_id, id, title, char_length(title) AS title_size, body, char_length(body) AS body_size from posts where user_id > 1 limit 10;
'''

with duckdb.connect('../posts_data.duckdb') as con:
    display(con.sql(sql_query).df())

,user_id,id,title,title_size,body,body_size
0,2,11,et ea vero quia laudantium autem,32,delectus reiciendis molestiae occaecati non mi...,169
1,2,12,in quibusdam tempore odit est dolorem,37,itaque id aut magnam\npraesentium quia et ea o...,152
2,2,13,dolorum ut in voluptas mollitia et saepe quo a...,50,aut dicta possimus sint mollitia voluptas comm...,225
3,2,14,voluptatem eligendi optio,25,fuga et accusamus dolorum perferendis illo vol...,144
4,2,15,eveniet quod temporibus,23,reprehenderit quos placeat\nvelit minima offic...,151
5,2,16,sint suscipit perspiciatis velit dolorum rerum...,67,suscipit nam nisi quo aperiam aut\nasperiores ...,185
6,2,17,fugit voluptas sed molestias voluptatem provident,49,eos voluptas et aut odit natus earum\naspernat...,136
7,2,18,voluptate et itaque vero tempora molestiae,42,eveniet quo quis\nlaborum totam consequatur no...,111
8,2,19,adipisci placeat illum aut reiciendis qui,41,illum quis cupiditate provident sit magnam\nea...,143
9,2,20,doloribus ad provident suscipit at,34,qui consequuntur ducimus possimus quisquam ame...,213